// Google Map
export const REACT_APP_GOOGLE_MAP_API_KEY =
  process.env.REACT_APP_GOOGLE_MAP_API_KEY || ''

// Firebase
export const REACT_APP_FIREBASE_API_KEY =
  process.env.REACT_APP_FIREBASE_API_KEY || ''
export const REACT_APP_FIREBASE_AUTH_DOMAIN =
  process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || ''
export const REACT_APP_FIREBASE_DATABASE_URL =
  process.env.REACT_APP_FIREBASE_DATABASE_URL || ''
export const REACT_APP_FIREBASE_PROJECT_ID =
  process.env.REACT_APP_FIREBASE_PROJECT_ID || ''
export const REACT_APP_FIREBASE_STORAGE_BUCKET =
  process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || ''
export const REACT_APP_FIREBASE_MESSAGING_SENDER_ID =
  process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID || ''
export const REACT_APP_FIREBASE_LOCAL_SERVER =
  process.env.REACT_APP_FIREBASE_LOCAL_SERVER || false

// GraphQL
export const REACT_APP_GRAPHQL_API_URL =
  process.env.REACT_APP_GRAPHQL_API_URL || ''
