name: Deploy to firebase
on: 
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: read
  issues: read
  pull-requests: read

jobs:
  deploy:
    env:
      VITE_GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
      VITE_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      VITE_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      VITE_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      VITE_GRAPHQL_API_URL: ${{ secrets.GRAPHQL_API_URL }}
      VITE_GRAPHQL_WEBSOCKET_URL: ${{ secrets.GRAPHQL_WEBSOCKET_URL }}
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
    runs-on: ubuntu-latest
    steps:
      - name: Into repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: yarn install
      - name: Create Production Build
        run: yarn build
      - name: Predeploy to firebase channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "smartcampus-1b31f"
          channelId: live