name: Deploy to firebase
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    env:
      REACT_APP_GOOGLE_MAP_API_KEY: ${{ secrets.GOOGLE_MAP_API_KEY }}
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_GRAPHQL_API_URL: ${{ secrets.GRAPHQL_API_URL }}
      REACT_APP_GRAPHQL_WEBSOCKET_URL: ${{ secrets.GRAPHQL_WEBSOCKET_URL }}
      REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
    runs-on: ubuntu-latest
    steps:
      - name: Into repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install firebase CLI
        run: npm install -g firebase-tools
      - name: Install Packages
        run: yarn install
      - name: Create Production Build
        run: yarn build
      - name: Predeploy to firebase channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "smartcampus-1b31f"
          channelId: live